version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    tty: true
    stdin_open: true
